- README.md
- docs/first_project.md
- docs/mlgit_commands.md
- docs/mlgit_internals.md
- docs/mutability_helper.md
- ml_git/commands/descriptor.py
- ml_git/config.py
- ml_git/constants.py
- ml_git/file_system/local.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/gdrive_store/test_32_gdrive_store.py
- tests/integration/helper.py
- tests/integration/output_messages.py
- tests/integration/test_19_create.py
- tests/integration/test_24_api.py
- tests/unit/test_config.py
We added the `--mutability` option to the `ml-git create` command, needed to set mutability during entity creation.
> Adding mandatory option to set mutability during entity creation

- ml_git/repository.py
- tests/integration/test_08_checkout_tag.py
- tests/integration/test_33_checkout_entity.py
Fixing a error ocurred when a checkout with parameters is done wrong, ml-git creates a sequence of empty directories.
> [bugfix] Moving directory creation to after checkout validity checks

- ml_git/_metadata.py
- ml_git/constants.py
Fixing error when internal git checkout fail because of 'HEAD is a detached symbolic reference'.
When status command is executed after commit command an error is raised and after that, the error persists blocking commands like, push or status.
Output:
ERROR - Repository: HEAD is a detached symbolic reference as it points to 'a7af6d1a3f5a2d92976e7e2eb3ce9827f52e3e83'
> Fixing 'HEAD is a detached symbolic reference' error

- ml_git/_metadata.py
- ml_git/admin.py
- ml_git/api.py
- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/commands/general.py
- ml_git/commands/remote.py
- ml_git/commands/utils.py
- ml_git/config.py
- ml_git/constants.py
- ml_git/file_system/local.py
- ml_git/metadata.py
- ml_git/ml_git_message.py
- ml_git/refs.py
- ml_git/repository.py
- ml_git/spec.py
- ml_git/utils.py
The ml-git code has been modified to work with `datasets`, `models `and `labels`.
```
ml-git --help
Usage: ml-git [OPTIONS] COMMAND [ARGS]...
Options:
--version  Show the version and exit.
Commands:
clone       Clone a ml-git repository ML_GIT_REPOSITORY_URL
datasets    Management of datasets within this ml-git repository.
labels      Management of labels sets within this ml-git repository.
models      Management of models within this ml-git repository.
repository  Management of this ml-git repository.
```
Logic has also been added to allow automatic updating of an old project. This logic changes the directories of the current project, the keys in the config file and also in the spec file of each entity.
**Example:** 
User workspace:
```
project/
├── dataset
│   └── dataset-ex1
├── labels …
```
> [plural entity names] Adding support to plural entity names

- ml_git/constants.py
- tests/unit/conftest.py
- tests/unit/test_admin.py
- tests/unit/test_config.py
- tests/unit/test_dir/.ml-git/config.yaml
- tests/unit/test_dir/datasets/dataex/dataex.spec
- tests/unit/test_dir/hdata/dataset-ex.spec
- tests/unit/test_dir/hdata/dataset-spec-3.spec
- tests/unit/test_dir/mdata/metadata/dataset-ex-2/dataset-ex-2.spec
- tests/unit/test_dir/mdata/metadata/dataset-ex/dataset-ex.spec
- tests/unit/test_dir/minit/datasets/index/metadata/dataset-ex/dataset-ex.spec
- tests/unit/test_dir/specdata/bad1/invalid-name.spec
- tests/unit/test_dir/specdata/invalid2.spec
- tests/unit/test_dir/specdata/invalid3.spec
- tests/unit/test_dir/specdata/invalid4.spec
- tests/unit/test_dir/specdata/noaa-severe-weather-inventory/noaa-severe-weather-inventory.spec
- tests/unit/test_dir/specdata/sample.spec
- tests/unit/test_dir/specdata/valid2.spec
- tests/unit/test_dir/udata/data.json
- tests/unit/test_dir/udata/data.yaml
- tests/unit/test_metadata.py
- tests/unit/test_refs.py
- tests/unit/test_spec.py
- tests/unit/test_utils.py
Depends on PR #69 .
Updating unit tests to use plural entity names and adding new tests for the project update scenario.
> [plural entity names] Updating unit tests to use plural entity names

- ml_git/repository.py
- ml_git/spec.py
- tests/unit/test_spec.py
Fixing an error that occurs when the user tries to use the create command with the `entity-dir` and `wizard-config` options together.
Observed behavior:
```
$ ml-git dataset create dataset-ex --mutability=strict --category=images --entity-dir=folderA/folderB --wizard-config
_ Current configured stores _
1 - s3 - mlgit-datasets
X = New Data Store
_Which store do you want to use (a number or new data store)? _ 1
ERROR - MLGit: 'dataset'
```
Fixed behavior:
```
$ ml-git dataset create dataset-ex --mutability=strict --category=images --entity-dir=folderA/folderB --wizard-config
_ Current configured stores _
1 - s3 - mlgit-datasets
X = New Data Store
_Which store do you want to use (a number or new data store)? _ 1
INFO - MLGit: Project Created.
```
> Fixing create command when used with entity_dir and wizard-config options

- ml_git/_metadata.py
- tests/integration/conftest.py
- tests/integration/test_05_add_files.py
- tests/integration/test_07_push_files.py
- tests/integration/test_35_status_short_mode.py
- tests/unit/conftest.py
- tests/unit/test_metadata.py
When run in a Windows environment, the tests show some errors related to file path and regex that become invalid.
**- Observed behavior:**
**Integration**
```
[gw0] [ 17%] FAILED tests/integration/test_07_push_files.py::PushFilesAcceptanceTests::test_04_push_with_wrong_repository
[gw4] [ 21%] FAILED tests/integration/test_05_add_files.py::AddFilesAcceptanceTests::test_10_add_command_with_metric_file
[gw2] [ 90%] FAILED tests/integration/test_35_status_short_mode.py::StatusShortModeAcceptanceTests::test_01_status_after_put_on_new_file_in_dataset
[gw2] [ 93%] FAILED tests/integration/test_35_status_short_mode.py::StatusShortModeAcceptanceTests::test_03_status_after_add_command_in_dataset
4 failed, 269 passed, 18 warnings in 1548.65s (0:25:48)
```
**Unit**
```
[gw0] [ 32%] FAILED …
```
> Fixing tests that fail when run in a Windows environment

- ml_git/storages/store_utils.py
During the process of adding remote storage through the command `ml-git repository storage add`, we noticed the `config.yml` file was being populated with extra information as shown below
```yaml
storages:
s3:
mlgit-datasets:
aws-credentials:
profile: default
region: us-east-1
s3h:
sagemaker-mlgit-data:
aws-credentials:
profile: null
endpoint-url: null
region:
LocationConstraint: us-west-1
ResponseMetadata:
HTTPHeaders:
content-type: application/xml
date: Wed, 19 May 2021 19:23:51 GMT
server: AmazonS3
transfer-encoding: chunked
x-amz-id-2: [removed]
x-amz-request-id: [removed]
HTTPStatusCode: 200
HostId: [removed]
RequestId: [removed]
RetryAttempts: 0
```
This fix makes the code use the `region['LocationConstraint']` instead of the `region` directly.
> Fixing issue in S3 bucket region

- ml_git/metadata.py
- ml_git/repository.py
- ml_git/spec.py
- tests/integration/test_05_add_files.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_07_push_files.py
- tests/integration/test_08_checkout_tag.py
- tests/integration/test_11_list_tag.py
- tests/integration/test_12_reset_command.py
- tests/integration/test_16_show.py
- tests/integration/test_24_api.py
- tests/integration/test_28_checkout_bare.py
- tests/unit/test_metadata.py
- tests/unit/test_spec.py
In the add command the user has an option (--bumpversion) that allows to increase the version of the entity. This increment is accomplished by adding one to the value of the version the user is in.
In some scenarios, this increment of one causes an error, since a tag with that specific version already exists - the user checked out tag 1 and tags 2 and 3 already exist, the --bumpversion would take the spec to point to version 2, but there is already a version 2.
This improvement makes the option able to identify the last version and define the version in the spec as the last plus one. In the scenario described above, bumpversion would make the spec point to version 4.
> Improvement in bumpversion option

- .github/PULL_REQUEST_TEMPLATE/pull_request.md
- README.md
Updated the readme documentation in the section on how to contribute, the correct contribution flow was added, forking it, creating a branch and socializing the PR.
Creation of a template for pull requests, when a pull request is created by default it becomes a template for the user to fill out and validate that all the steps for opening the PR have been carried out correctly.
> How to contribute documentation

- scripts/resources_initialization/resources_initialization.bat
- scripts/resources_initialization/resources_initialization.sh
When the script initialize and ask for username **(ex: user-mlgit)**, and the profile of this user is different from username **(ex: UserMlgit)**, the script is showing wrong message:
```
What name do you want to give for the repository with these configurations? [default: tests-scripts-mlgit-repository] 
[master (root-commit) 59a8e19] Initial commit with .ml-git configured
1 file changed, 7 insertions(+)
create mode 100644 .ml-git/config.yaml
remote: Repository not found.
fatal: repository 'https://github.com/user-mlgit/tests-scripts-mlgit-repository.git/' not found
Repository creation done. Go to https://github.com/user-mlgit/script-test-mlgit-repository to see.
If you want to start an ml-git project with these settings you can use:
ml-git clone …
```
> Fixing wrong message when resources initialization script fails

- ml_git/constants.py
- ml_git/file_system/index.py
- ml_git/file_system/local.py
- ml_git/metadata.py
- ml_git/ml_git_message.py
- ml_git/utils.py
- tests/integration/helper.py
- tests/integration/test_05_add_files.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_08_checkout_tag.py
- tests/integration/test_09_status_command.py
- tests/unit/test_utils.py
Inside an entity's directory it is possible that the user has files that he does not want to version. With that in mind, this PR adds support for defining the `.mlgitignore` file which should define rules to indicate which files should be ignored.
The `.mlgitignore` file must be defined in the entity root folder. This means that each entity can have its `.mlgitignore` file, and the defined rules will only be valid for files inside the entity dir.
workspace structure example:
```
project/
├── datasets
│      └── dataset-ex
│          └── data
│              └── file.png
│              └── file.txt
│              └── file2.txt
│              └── augmented
│                  └── file.png
│          └── dataset-ex.spec
│          └── .mlgitignore <- HERE
├── .ml-git
│    ├── datasets
└──  └── …
```
> Adding support for defining the .mlgitignore file

- Makefile
- ml_git/_metadata.py
- ml_git/admin.py
- ml_git/constants.py
- ml_git/git_client.py
- ml_git/ml_git_message.py
- tests/integration/conftest.py
Added the correction of ssh key password support for the problem found when using ml-git in repositories configured with ssh that need a password, in this case, a popup should be displayed for the user to inform the password to his ssh key, only in the terminals of windows (CMD and Powershell) these passwords were not requested, making it impossible for ml-git to perform any iteration with it.
> Adding support to password-protected ssh keys

- tests/integration/gdrive_storage/test_32_gdrive_storage.py
The bumpversion option in add command when used at the first version it will not increment the version, then the test was adjusted to expect the version 1 instead 2.
> Adjustmenting gdrive integration tests

- docs/mlgit_commands.md
- ml_git/_metadata.py
- ml_git/commands/repository.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/test_17_list.py
When the user uses the `list` command on a project that doesn't have any versioned entities, the command reports that there are no entities but treats this as an `ERROR`. The behavior has been changed to be an `INFO`.
**Command:**
```
$ ml-git datasets list
```
**Observed output:**
```
ERROR - Repository: You don't have any entity beign managed.
A complete log of this run can be found in: ml-git_execution.log.2021-08-30
```
**Fixed output:**
```
INFO - Repository: You don't have any entity beign managed.
```
Also in this branch a typo found in the help of the `repository init` command has been fixed.
>  Changing the message level in the list command

- ml_git/commands/descriptor.py
When the user types **ml-git datasets --help** command some help messages are displayed with ellipsis
**Note**: the same issue happens when executing the commands **ml-git models --help** and **ml-git labels --help**
Current output:
Expected output:
There is an issue [here](https://github.com/pallets/click/issues/486) reporting the problem and the solution.
> Fixing help messages with ellipsis

- Pipfile
- Pipfile.lock
- README.md
Pipfile.lock needs to be generated with the minimum supported version of python (3.6.1).
Also, an inconsistency in the installation process was observed when using the `setup.py` file, so that the user had a better experience, the documentation was updated to suggest the use of `pip`.
> Updating Pipfile.lock and How to Install section

- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- tests/integration/test_05_add_files.py
- tests/integration/test_29_log.py
The metrics option is only supported for models but displayed when inserting the command "ml-git datasets add --help" or "ml-git labels add --help".
> Remove metric options from add command for dataset and labels

- ml_git/_metadata.py
- ml_git/git_client.py
- ml_git/ml_git_message.py
It has been observed that in some scenarios (listed below) ml-git is not able to forward git's request for user credentials. This PR adjusts the behavior to allow the user to enter the necessary credentials.
The following error scenarios were observed:
- Windows user in CMD or PowerShell, using ssh key protected with passphrase, and did not configure ssh-agent to store the key.
- Windows user in CMD or PowerShell, using https without having the credential manager configured.
```
$ ml-git datasets push dataset-ex
INFO - Metadata Manager: Metadata init [...] @ [...]
ERROR - Repository: Permission denied (publickey). Please make sure you have the correct access rights and the repository exists.
``` …
> Fixing the user's git credential input

- ml_git/git_client.py
- tests/integration/test_04_init_entity.py
When the user tries to run commands like **ml-git datasets init** or **ml-git repository graph** inside a project folder with blank spaces in its name and there are no entities initialized yet, it's displayed a repository error.
The problem is related with the internal git clone command
> Fixing issue when ml-git tries to clone ml entities repository and there are blank spaces in the project folder path

- ml_git/ml_git_message.py
- ml_git/storages/s3_storage.py
- tests/integration/test_07_push_files.py
Currently if the user tries to execute the push command setting an endpoint-url to a minio service that is not running the following error is shown (this error is not logged by ml-git):
This PR add an error log reporting the problem:
> Add error log message when using a minio endpoint that is not running

- ml_git/file_system/local.py
- tests/integration/test_36_status_path_directory.py
It was observed that when the user passes an invalid directory to the `ml-git status` command, the system displays an error and all subsequent commands related to the entity also display an error.  This PR fixes this issue.
```
$ ml-git datasets status dataset-ex wrong-dir
INFO - Repository: datasets: status of ml-git index for [dataset-ex]
ERROR - Repository: The directory informed is invalid.
ERROR - Repository: 'NoneType' object is not iterable
$ ml-git datasets status dataset-ex data
ERROR - Repository: HEAD is a detached symbolic reference as it points to '3ff98394823ae923e84bc'
A complete log of this run can be found in: …
```
> Fixing invalid directory handling in status command

- docs/advanced_scenarios.md
- docs/first_project.md
- docs/first_steps.md
- docs/qs_configure_repository.md
Updating in the docs all the usages of the command `$ ml-git repository storage add` to always have the `--endpoint-url` parameter which indicates the usage o MinIO.
> Updating docs to use MinIO by default

- docs/aws_s3_configuration.md
- docs/first_project.md
- docs/minio_s3_configuration.md
- docs/storage_configurations.md
- mkdocs.yml
Separating the documentation of how to set up S3 in two different files, one for AWS S3 and one for MinIO.
> Updating docs to teach how to configure MinIO

- .github/workflows/release-workflow.yml
The release workflow was using python 3.7, since the Pipfile points to version 3.6 the pipenv command returns an error for not having the desired version. The workflow was updated to be able to perform the steps in version 3.6.
>  Fixing Python version in release workflow

- ml_git/commands/descriptor.py
- tests/integration/test_19_create.py
Now anything outside of the defined range will be throwing the error presented in the image.
> Adding range validator to --version parameter of the create command

- ml_git/repository.py
In the create command the user has the possibility to use the wizard option to be asked interactively about the configurations that need to be used in the entity. If, during the input process, the user aborts the command (CTRL+C or something like that), the files that have already been created during execution remain in the user's workspace. 
This PR aims to correct this behavior by removing these files from the workspace, as it considers them to be garbage.
> Removing files created during an aborted command execution

- ml_git/config.py
- ml_git/repository.py
- tests/unit/conftest.py
- tests/unit/test_config.py
Was observed that an error was being returned ('NoneType' object is not subscriptable) when trying to configure an sftp bucket using the `--wizard-config` option of the create command. This PR fixes this issue. In addition, a refactoring was performed on the wizard methods to decouple code and structure user input.
```
$ ml-git models create models-ex --categories=test --mutability=strict --wizard-config
_ Current configured storages _
1 - s3h - test-bucket
X - New Data Storage
_Which storage do you want to use (a number or new data storage)? _ x
Please specify the storage type ['s3', 's3h', 'azureblobh', 'gdriveh', 'gdrive', 'sftph']: _ sftph
Please specify the bucket name: _ sftph
Please specify the git repository for ml-git models metadata: _ sftph-repository …
```
> Fixing the problem of configuring an sftp bucket with the wizard option

- ml_git/config.py
- tests/unit/test_config.py
Depends on: https://github.com/HPInc/ml-git/pull/173
If the user executes the create command with the option --wizard-config, selects the option 'X' to create a new data storage and selects the storage type s3h, the information is saved in the global configuration file '.mlgitconfig ' instead of local configuration file.
This PR fixes this problem. Now the storage is saved in its correct place (local configuration file).
> Fixing issue related with storage type s3h being saving in global configuration instead of local configuration

- README.md
- docs/advanced_scenarios.md
- docs/aws_s3_configuration.md
- docs/azure_configurations.md
- docs/first_project.md
- docs/first_steps.md
- docs/gdrive_configurations.md
- docs/installation_guide.md
- docs/minio_s3_configuration.md
- docs/mlgit_commands.md
- docs/qs_checkout.md
- docs/qs_configure_repository.md
- docs/sftp_configurations.md
Special character in documentation is inducing the error of copying and pasting.
> Removing special character from commands documentation

- docs/api/README.md
- docs/api/api_scripts/basic_flow.ipynb
- docs/api/api_scripts/clone_repository.ipynb
- docs/api/api_scripts/mnist_notebook/mnist_random_forest_api.ipynb
- docs/api/api_scripts/multiple_datasets_notebook/checkout_with_sample.ipynb
- docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
- docs/api/api_scripts/relationship_notebook/relationship_api_commands.ipynb
- docs/api/quick_start.md
- ml_git/api.py
- tests/integration/test_24_api.py
This PR creates a class in the ML-Git API to hold the root path of a project so that every command of the API can run in the context of said project.
This happens because of the decorator that is automatically added to all methods within the class by its Metaclass, the decorator is responsible for: changing the current dir to the project root, executing the command, changing the current dir back to the origin.
The decorator was implemented using the `pathlib.Path` class, which means that we can tell the API the project root by using: a relative path, an absolute path, or the current working directory (CWD) by not passing any path.
An important thing to keep in mind is that the decorator can only work in the class methods that have the parameter self because the decorator needs to access …
> Creating MLGitAPI to allow multiple projects in the same script

- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/test_05_add_files.py
When the user executes the add command on an entity that has corrupted files, ML-Git informs that these corrupted files were not added. In this PR the list of files was adjusted to be grouped by directories.
**Proposed output:**
```
$ ml-git datasets add dataset-ex10
INFO - Metadata Manager: Pull [D:\Virtus\demo\.ml-git\datasets\metadata]
INFO - Repository: datasets adding path [D:\Virtus\demo\datasets\dataset-ex] to ml-git index
files: 100%|██████████████████| 113/113 [00:00<00:00, 934files/s]
files: 100%|██████████████████| 113/113 [00:00<00:00, 109kfiles/s]
WARNING - Repository: There are corrupted files in your workspace. These files were not added. Files:
data/   ->      6 FILES
data2/  ->      6 FILES
INFO - Repository: You can view the complete list of corrupted files at …
```
> Updating add command output when it has corrupt files

- ml_git/api.py
- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/file_system/local.py
- ml_git/repository.py
- tests/integration/test_33_checkout_entity.py
This PR adds handling to the file listing when the user has unsaved files in their workspace and tries to checkout an entity.
Also, the --full option was added in case he wants to have the complete listing of the files.
```
$ ml-git datasets checkout dataset-ex
INFO - Metadata: Performing checkout in tag images__dataset-ex__2
WARNING - MLGit: Your local changes to the following files would be discarded:
data/     ->      8 FILES
data2/    ->      8 FILES
INFO - Local Repository: Please, commit your changes before the get. You can also use the --force option to discard these changes. See 'ml-git --help'.
```
With the --full option the user gets a output similar to the current output
```
$ ml-git datasets checkout dataset-ex --full
INFO - Metadata: Performing checkout in tag …
```
> Updating checkout command output when it has unsaved files

- ml_git/commands/descriptor.py
- tests/integration/test_05_add_files.py
It was observed that when passing the --metrics-file option with an empty value, the command is executed without informing the user of the error.
```
$ ml-git models add model-ex --metrics-file=
INFO - Metadata Manager: Pull [D:\demo\.ml-git\models\metadata]
INFO - Repository: models adding path [D:\demo\models\model-ex] to ml-git index
files: 100%|██████████████████████████████████| 1.00/1.00 [00:00<00:00, 66.7files/s]
files: 100%|██████████████████████████████████| 1.00/1.00 [00:00<?, ?files/s]
```
**Fixed behavior:**
```
$ ml-git models add model-ex --metrics-file=
Usage: ml-git models add [OPTIONS] ML_ENTITY_NAME [FILE_PATH]...
Error: Invalid value for "--metrics-file": Value cannot be empty.
```
> Adding validation for empty string in metrics-file option

- ml_git/file_system/local.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/test_13_remote_fsck.py
- tests/unit/test_local.py
An error was observed when the user try to execute the remote-fsck for an empty entity:
```
$ ml-git datasets remote-fsck dataset-ex
'NoneType' object has no attribute 'split'
```
As a fix, a treatment was added to this case:
```
$ ml-git datasets remote-fsck dataset-ex
WARNING - Local Repository: The entity dataset-ex has no data to be checked. You have to commit some data before executing this command.
```
> Adding message when executing remote-fsck for empty entity

- ml_git/file_system/local.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/test_05_add_files.py
It was observed that when passing the --metrics-file option with an empty csv file, the command return an unhandled error. This PR adds a handling message for this scenario and other possible errors.
```
$ ml-git models add model-ex --metrics-file=D:\empty.csv
list index out of range
```
**Fixed behavior:**
```
$ ml-git models add model-ex --metrics-file=D:\empty.csv
ERROR - Repository: It was not possible to obtain the metrics of the informed file, please check if the file is correctly.
```
> Adding handling for invalid csv file in add command

- ml_git/repository.py
- tests/integration/test_14_fsck.py
It was observed that when executing the fsck command in a directory that does not have an initialized ml-git project or that the command entity has not been initialized, the user did not receive adequate feedback. This PR added handling for these scenarios.
**Uninitialized Project:**
```
$ ml-git datasets fsck
ERROR - Repository: You are not in an initialized ml-git repository.
```
**Uninitialized Entity:**
```
$ ml-git datasets fsck
ERROR - Repository: The datasets doesn't have been initialized.
```
> Adding treatments in fsck command for repository and entity uninitialized

- docs/mlgit_commands.md
- ml_git/commands/descriptor.py
- ml_git/file_system/local.py
- ml_git/ml_git_message.py
- tests/integration/test_13_remote_fsck.py
It was observed that when using the `remote-fsck` command and detecting the missing of some IPLD, even with the `--full` option, the user could not see the list of missing files.
This PR has added treatment messages to inform the user that he can use the `--full` option to view the full list, and once he has used it, a message presenting the full list.
**Without --full option:**
```
$ ml-git models remote-fsck model-ex
iplds: 100%|████████████████████████████████| 1.00/1.00 [00:00<00:00, 1.87iplds/s]
INFO - Local Repository: 1 missing descriptor files. Consider using the --thorough option.
INFO - Local Repository: You can use the --full option to see the complete list of missing descriptor files.
blobs: 100%|████████████████████████████████| 2.00/2.00 [00:00<00:00, 667blobs/s]
INFO - …
```
> Adding message to show the list of missing IPLD

- ml_git/repository.py
- tests/integration/test_05_add_files.py
It was observed that when executing the `add` command in a directory that has not yet started an ml-git project, the tool's output does not match the real error and did not follow the pattern of the other commands.
```
$ ml-git datasets add dataset-ex
ERROR - Repository: .ml-git/config.yaml invalid. It should look something like this:
storages:
s3h:
somebucket:
aws-credentials:
profile: someprofile
region: someregion
```
**Fixed behavior:**
```
$ ml-git datasets add dataset-ex
ERROR - Repository: You are not in an initialized ml-git repository.
```
> Checking if the user is in a valid directory when running the add command

- ml_git/commands/custom_options.py
- ml_git/commands/wizard.py
- ml_git/ml_git_message.py
- tests/integration/test_19_create.py
- tests/integration/test_38_models_metrics.py
**Observed behaviour:**
```
$ ml-git datasets create dataset-ex --import-url='test' --categories=test --mutability=strict
Usage: ml-git datasets create [OPTIONS] ARTIFACT_NAME
Error: Missing option "--credentials-path". The option `credentials_path` is required if `import-url` is used.
```
**Fixed behaviour:**
```
$ ml-git datasets create dataset-ex --import-url='test' --categories=test --mutability=strict
The option `credentials-path` is required if `import-url` is used. Please, inform the value for the `credentials-path`:
```
> Prompt user for values for dependent options

- ml_git/commands/custom_types.py
- ml_git/ml_git_message.py
- tests/integration/test_19_create.py
**Observed behaviour:**
```
$ ml-git datasets create dataset=ex
At least one category must be defined. The categories' names must be comma-separated. Please inform the value for the categories option: wrong name
Error: wrong name
```
**After adjustments:**
```
$ ml-git datasets create dataset=ex
At least one category must be defined. The categories' names must be comma-separated. Please inform the value for the categories option: wrong name
Error: The value 'wrong name' is invalid. A category cannot contain blank space, special characters, and punctuation characters.
```
> Updating the error message when identifying an invalid category

- README.md
- docs/mlgit_commands.md
- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/commands/help_msg.py
- ml_git/commands/storage.py
- ml_git/commands/wizard.py
- ml_git/ml_git_message.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_19_create.py
- tests/integration/test_40_wizard_config.py
This PR adds a `--wizard` flag to launch the wizard on commands that support it. The following commands have been modified:
- ml-git <entity> add 
- ml-git <entity> commit
- ml-git <entity> create
- ml-git repository storage add
Usage example without the flag:
```
$ ml-git datasets create data-demo
Usage: ml-git datasets create [OPTIONS] ARTIFACT_NAME
Error: Missing option "--categories".
```
Usage example with the flag:
```
$ ml-git datasets create data-demo --wizard
At least one category must be defined. The categories' names must be comma-separated. Please inform the value for the categories option: demo
An entity must have a defined mutability. Please inform the value for the mutability option (strict, flexible, mutable): strict
INFO - MLGit: Dataset artifact created.
```
>  Adding the wizard option to commands that support it

- ml_git/file_system/objects.py
- ml_git/metadata.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- ml_git/utils.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_23_metadata_persistence.py
- tests/integration/test_24_api.py
- tests/integration/test_29_log.py
- tests/integration/test_33_checkout_entity.py
- tests/integration/test_38_models_metrics.py
```
$ ml-git datasets commit dataset-ex
WARNING - Repository: Nothing to commit (create/add files and use "ml-git datasets add" command to track this files)
```
**Behaviour before fix:**
```
$ ml-git datasets commit dataset-ex
INFO - Metadata Manager: Commit repo[D:\demo\.ml-git\datasets\metadata] --- file[dataset-ex]
```
> Adding treatment for commit attempt with no data to commit

- ml_git/config.py
- ml_git/ml_git_message.py
- tests/unit/test_config.py
It was observed that when using the `--wizard-config` option of the create command, the fields that the user pressed enter were filled with `''`. However, the storage name field is mandatory and must be other than empty.
In addition, the other fields, when not informed, must be filled with the value `null` instead of `''`.
When filling with `''`, it was also observed that the value for a sftp storage port ended up generating an error.
**config.yaml before fix:**
```
datasets:
git: [GIT-URL]
labels:
git: [GIT-URL]
models:
git: [GIT-URL]
storages:
s3h:
'':
aws-credentials:
profile: ''
endpoint-url: ''
region: ''
```
**WARNING message added when empty is informed for the bucket name:**
```
$ ml-git datasets create dataset-ex --categories=test --mutability=strict --wizard-config
Currently …
```
> Adding method to validate the input in the wizard-config option of create

- ml_git/metadata.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- tests/integration/test_06_commit_files.py
```
$ ml-git datasets commit dataset-ex --version=2
WARNING - Repository: Nothing to commit (create/add files and use "ml-git datasets add" command to track this files)
```
**Behaviour before fix:**
```
$ ml-git datasets commit dataset-ex --version=2
INFO - Multihash: File dataset-ex.spec has been automatically added to staged files.
WARNING - Repository: Nothing to commit (create/add files and use "ml-git datasets add" command to track them)
```
> Checking if have new data before change version in spec

- README.md
- docs/first_project.md
- docs/first_steps.md
- docs/mlgit_commands.md
- docs/qs_checkout.md
- ml_git/admin.py
- ml_git/commands/general.py
- ml_git/ml_git_message.py
- tests/integration/test_20_clone.py
- tests/integration/test_33_config.py
In this PR the `--folder` option was removed from the clone command. To maintain support for creating directories, the optional argument `[DIRECTORY]` has been added. 
```
Usage: ml-git clone [OPTIONS] REPOSITORY_URL [DIRECTORY]
Clone an ml-git repository ML_GIT_REPOSITORY_URL
Options:
--untracked  Does not preserve git repository tracking.
--verbose    Debug mode
```
> Updating clone command to receive directory as argument

- ml_git/api.py
- ml_git/commands/prompt_msg.py
- ml_git/commands/storage.py
- ml_git/config.py
- ml_git/constants.py
- ml_git/ml_git_message.py
- ml_git/repository.py
- ml_git/storages/sftp_storage.py
- tests/integration/test_19_create.py
- tests/unit/test_config.py
In this PR we changed the create command wizard to assist the user during the creation of a storage.
**Creating s3h storage:**
```
$ ml-git datasets create dataset-ex --wizard
At least one category must be defined. The categories' names must be comma-separated. Please inform the value for the categories option: demo
An entity must have a defined mutability. Please inform the value for the mutability option (strict, flexible, mutable): strict
Select the storage where this entity's data should be stored:
[X] - New Data Storage Configuration
Which storage do you want to use (a number or new data storage)? X
Define the storage type (s3h, azureblobh, gdriveh, sftph) [s3h]: s3h
Define the storage name: demo-s3h
Define the profile to be used to connect to S3 [default]:
If you are using MinIO …
```
> Updating the create command wizard to help with storage configuration

- ml_git/config.py
- ml_git/ml_git_message.py
- ml_git/utils.py
- tests/integration/test_19_create.py
- tests/unit/test_utils.py
```
$ ml-git datasets create data-out --categories=test --mutability=strict --entity-dir=../
ERROR - MLGit: The entity data directory must be inside the ml-git project entities directory. '../' is not a valid value.
```
> Adding validation to the informed directory for entity creation

- ml_git/commands/wizard.py
- tests/integration/test_06_commit_files.py
```
$ ml-git labels commit labels-ex --wizard
Define the labels version to be commited [3]:
Define the commit message:
Do you want to link a dataset entity to this version of the labels set [y/N]? y
Define the dataset name to be linked:                 <- BLANK SPACES HERE
INFO - MLGit: Value cannot be empty.
Define the dataset name to be linked: dataset-ex
INFO - Multihash: File labels-ex.spec has been automatically added to staged files.
INFO - Local Repository: Associate datasets [dataset-ex]-[test__dataset-ex__2] to the labels.
INFO - Metadata Manager: Commit repo[D:\demo\.ml-git\models\metadata] --- file[labels-ex]
```
**Behaviour before fix:**
```
$ ml-git labels commit labels-ex --wizard
Define the labels version to be commited [3]:
Define the commit …
```
> Adding validation for empty value in required options in wizard prompt

- ml_git/file_system/index.py
- ml_git/manifest.py
- ml_git/ml_git_message.py
- tests/integration/test_05_add_files.py
With this change it is now possible to identify when a file is manually corrected in the workspace by the user.
> Updating add command to save previous hash when detect corrupted files

- ml_git/ml_git_message.py
With this PR, the checkout info message was modified from (OLD):
➜ ml-git datasets checkout test-dataset
Define the dataset version to be downloaded [latest]:
INFO - Metadata: Performing checkout on the entity's lastest tag (test__test-dataset__1)
INFO - Repository: already at tag [test__test-dataset__1]
too (NEW):
➜ ml-git datasets checkout test-dataset
Define the dataset version to be downloaded [latest]:
INFO - Metadata: Performing checkout on the entity's latest tag [test__test-dataset__1]
INFO - Repository: Already at tag [test__test-dataset__1]
where were made 3 changes, 2 on Metadata INFO and one in Repository INFO
> Fixing typo error in checkout info message

- ml_git/ml_git_message.py
This PR modify the error message of command checkout from [OLD]:
No entity with that name was found.
to [NEW]:
No tag was found for that entity.
> Updating no-tags found error message to checkout command

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/deploy_mkdocs.yml
- .github/workflows/publish-release.yml
- .github/workflows/release-workflow.yml
Recently github started using Ubuntu 22.04 as the latest, and because of that, the settings with python 3.6 stopped working. In this PR we set the version used for 20.04, which was used by this project so far.
> Fixing ubuntu version in workflows
