- ml_git/_metadata.py
- ml_git/file_system/local.py
- ml_git/repository.py
- tests/integration/conftest.py
- tests/integration/test_08_checkout_tag.py
- tests/unit/conftest.py
- tests/unit/test_metadata.py
Changes to make ml-git call the default branch of a metadata repository, instead of the master branch.
> Change hardcoded branch master to default branch

- .github/workflows/release-workflow.yml
- Pipfile
- Pipfile.lock
- scripts/build/compile/build.bat
Updating github actions and windows build script after github security update.
> Fixing github actions and windows build script

- docs/first_project.md
- scripts/resources_initialization/README.md
- scripts/resources_initialization/resources_initialization.bat
- scripts/resources_initialization/resources_initialization.sh
This script aims to facilitate the creation of resources (buckets and repositories) that are needed for ml-git.
Flow example:
```
$ ./resources_inicialization.sh
What is your github username? lucasncabral
If you are working with github enterprise, type the enterprise url, if not press enter to continue [default:https://github.com]: 
What is your project name? my-project
What is your organization name? [default: will create in the user account]
Do you want to create a remote repository for dataset? (Y/n) Y
What name do you want to give to your remote repo? [default: my-project-mlgit-dataset]
Repository creation done. Go to https://github.com/lucasncabral/my-project-mlgit-dataset to see.
Do you want to create a remote repository for labels? (Y/n) Yes
What name do you want to give to your …
```
> Creating script to automate the creation of repos and buckets

- README.md
- docs/first_project.md
Updating the demo videos by replacing deprecated options/commands.
Changes:
`dataset` -> `datasets`
`model `-> `models`
`store `-> `storage`
`--version-number` -> `--version`
> Updating demo videos

- tests/unit/conftest.py
- tests/unit/test_admin.py
- tests/unit/test_azure_store.py
- tests/unit/test_config.py
- tests/unit/test_dir/.ml-git/config.yaml
- tests/unit/test_dir/dataset/dataex/dataex.spec
- tests/unit/test_dir/hdata/config.yaml
- tests/unit/test_dir/hdata/dataset-ex.spec
- tests/unit/test_dir/hdata/dataset-spec-3.spec
- tests/unit/test_dir/mdata/metadata/dataset-ex-2/dataset-ex-2.spec
- tests/unit/test_dir/mdata/metadata/dataset-ex/dataset-ex.spec
- tests/unit/test_dir/minit/dataset/index/metadata/dataset-ex/dataset-ex.spec
- tests/unit/test_dir/specdata/bad1/invalid-name.spec
- tests/unit/test_dir/specdata/invalid1.spec
- tests/unit/test_dir/specdata/invalid2.spec
- tests/unit/test_dir/specdata/invalid3.spec
- tests/unit/test_dir/specdata/invalid4.spec
- tests/unit/test_dir/specdata/noaa-severe-weather-inventory/noaa-severe-weather-inventory.spec
- tests/unit/test_dir/specdata/sample.spec
- tests/unit/test_dir/specdata/valid.spec
- tests/unit/test_dir/specdata/valid2.spec
- tests/unit/test_dir/udata/data.json
- tests/unit/test_dir/udata/data.yaml
- tests/unit/test_gdrive_store.py
- tests/unit/test_hashfs.py
- tests/unit/test_local.py
- tests/unit/test_metadata.py
- tests/unit/test_s3_store.py
- tests/unit/test_spec.py
- tests/unit/test_utils.py
> [redefine storage setup] Updating unit tests to use storage instead of store

- README.md
- docs/api/README.md
- docs/api/api_scripts/basic_flow.ipynb
- docs/api/api_scripts/multiple_datasets_notebook/multiple_datasets.ipynb
- docs/api/quick_start.md
- docs/centralized_cache_and_objects.md
- docs/developer_info.md
- docs/first_project.md
- docs/gdrive_configurations.md
- docs/mlgit_commands.md
- docs/mlgit_internals.md
- docs/mutability_helper.md
- docs/plugins.md
- docs/qs_configure_repository.md
>  [redefine storage setup] Updating documentation to use storage instead of store

- README.md
- docker/README.md
- docs/api/quick_start.md
- docs/azure_configurations.md
- docs/gdrive_configurations.md
- docs/qs_configure_repository.md
- docs/quick_start.md
- docs/s3_configurations.md
- docs/tabular_data/tabular_data.md
- mkdocs.yml
New changes regarding naming standard.
> Additional minor changes to ML-Git documents

- docs/resources_initialization.md
- scripts/resources_initialization/resources_initialization.bat
- scripts/resources_initialization/resources_initialization.sh
Implementation of minio bucket configuration support on resource initialization script.
> Minio resource initialization

- docs/first_project.md
- docs/mlgit_commands.md
- docs/qs_configure_repository.md
Fixed some incorrect code examples in the documentation
> Fixing some command erros in the docs

- ml_git/git_client.py
Rerun command when the SSH host is not known and git throws an error.
> Fixing error when ssh host is first accessed

- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/repository.py
Creating interface to diff command in the ml-entities. 
This command will show the differences between two specific tags.
Usage:
ml-git datasets diff imagenet8 tag1 tag2
> Initial implementation of diff command

- docs/mlgit_commands.md
Depends on: https://github.com/HPInc/ml-git/pull/180
Creating documentation about diff command in the mlgit_commands.md file.
> Inserting documentation about diff command

- docs/api/README.md
- docs/api/quick_start.md
Updating API documentation to explain and use the new ML-Git API
> Updating documentation to work with the MLGitAPI class

- docs/api/api_scripts/multiple_projects.ipynb
Creation of multiple projects notebook example to work with the MLGitAPI class.
> Creation of notebook example to work with the MLGitAPI class

- docs/api/README.md
- docs/first_project.md
- docs/mlgit_commands.md
This PR updates the documentation to conform to changes made to:
- #194 
- #195
- #196 
- #197
> Updating documentation to reflect changes in command outputs

- ml_git/commands/descriptor.py
- ml_git/commands/storage.py
- ml_git/commands/wizard.py
This PR adds the possibility of using the wizard to --port option in SFPTH storage, and modifying the wizard method to support default values.
> Adding use of wizard to port on SFPTH storage

- ml_git/commands/entity.py
- ml_git/commands/prompt_msg.py
- ml_git/commands/utils.py
- ml_git/commands/wizard.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_23_metadata_persistence.py
- tests/integration/test_40_wizard_config.py
```
$ ml-git models commit models-ex
Define the model version to be commited [10]: 
Define the commit message: My commit message
Do you want to link a dataset entity to this version of the model set [y/N]? y
Define the dataset name to be linked: dataset-ex
Do you want to link a labels entity to this version of the model set [y/N]?
INFO - Multihash: File models-ex.spec has been automatically added to staged files.
INFO - Local Repository: Associate datasets [dataset-ex]-[test__dataset-ex__2] to the models.
INFO - Metadata Manager: Commit repo[D:\demo\.ml-git\models\metadata] --- file[models-ex]
```
> Prompting the version number and message in the commit command

- docs/mlgit_commands.md
- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/commands/help_msg.py
- ml_git/commands/prompt_msg.py
- ml_git/commands/utils.py
- ml_git/commands/wizard.py
- tests/integration/test_33_checkout_entity.py
```
$ ml-git models checkout model-ex --wizard
Define the dataset version to be downloaded [latest]: 5
Do you want to checkout related dataset [y/N]?
Do you want to checkout related labels [y/N]?
```
> Updating checkout command to prompt version and related entities

- ml_git/commands/descriptor.py
- ml_git/commands/entity.py
- ml_git/file_system/objects.py
- ml_git/repository.py
- tests/integration/test_06_commit_files.py
- tests/integration/test_40_wizard_config.py
```
$ ml-git datasets commit dataset-ex --wizard
WARNING - Repository: Nothing to commit (create/add files and use "ml-git datasets add" command to track them)
```
**Behaviour before fix:**
```
$ ml-git datasets commit dataset-ex --wizard
Define the dataset version to be commited [1]:
Define the commit message:
WARNING - Repository: Nothing to commit (create/add files and use "ml-git datasets add" command to track them)
```
> Checking if there is data to be commited before prompting information

- .pre-commit-config.yaml
To use pre-commit, you need:
1. Install pre-commit:
```
pip install pre-commit
```
2. Install git hooks in your `.git/`, from ml-git root directory:
```
pre-commit install
```
> Adding pre-commit configuration
